platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SDWebImage', '~>3.7'
pod "GLPubSub", "~> 1.0"
pod 'pop', '~> 1.0.7'
pod 'MJRefresh'
pod 'TMCache', '~> 2.0.0'
pod 'FMDB', '~> 2.5'
pod 'SDWebImage', '~> 3.7.2'
pod 'MJExtension'
pod 'MagicalRecord', '~> 2.3.0'